language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: test
      node_js: "10"
      name: eslint
      script:
        - npm ci
        - npm run eslint
    - node_js: "10"
      name: prettier
      script:
        - npm ci
        - npm run prettier
